spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/serverdb
    username: extrieve
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true