spring:
  datasource:
    username: extrieve
    password: password
    hostname: 127.0.0.1
    port: 3306
    url: jdbc:mysql://
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true